### ISSUE TITLE
Range Slider Styling Question

### ISSUE THREAD

**Issue by SolaOmi** [socialtables/2019-drawing-app-challenge#3]
Hey Team socialTables!

I have quick question about the style changes we're suppose to make to match the given design. For the range slider that controls the Stroke Width in the Pen panel, are we suppose to match the design exactly (circular knob) or can we just use the native html [input of type range](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) (rectangular knob).

Best,
Bisola

P.S. I tried to email the given address in the readme, and it bounced back. Got a response from Postmaster that said only members of the organization or people on the senders list.

**Comment by timfoley** [comment]
Hi @SolaOmi ! You can absolutely use the native html range input for that.

And thanks for the note about the email. We'll look into that right away!

**Comment by SolaOmi** [comment]
Thanks
