### ISSUE TITLE
accessing AWS s3 needs credentials

### ISSUE THREAD

**Issue by johnbryant** [socialtables/2019-drawing-app-challenge#6]
When I tried to upload image to s3 bucket named **socialtables-apprenticeship**,  the server return the error message of "Missing credentials in config". Then I googled the reasons, someone said that I need the **accessKeyId** and **secretAccessKey**, do I need to create them by myself or you can provide this informations.
Thanks!

![image](https://user-images.githubusercontent.com/5527451/61922563-ed884d00-af2e-11e9-9a92-552605806a46.png)

**Comment by jschultz21** [comment]
hey @johnbryant, thanks for pointing this out! Due to some confusion and permissions issues we've removed this as a bonus option. Sorry!

**Comment by johnbryant** [comment]
@jschultz21 Thanks for the reply!
